#application.yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tokens
    driverClassName: org.postgresql.Driver
    username: tokens
    password: tokens
    hikari:
      connection-timeout: 20000 # maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 60          # minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 60     # maximum pool size
      idle-timeout: 1000        # maximum idle time in milliseconds for a connection
      max-lifetime: 1000        # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true         # default auto-commit behavior.
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: non_null

app:
  persistence: postgres
